import asyncHandler from 'express-async-handler'
import User from '../models/userModel.js'
import bcrypt from 'bcryptjs'
// import { sendToken } from '../utils/sendToken.js'
import jwt from 'jsonwebtoken'
